version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --init-file /data/application/init-db.sql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations/init-db.sql:/data/application/init-db.sql

  rabbitmq:
    platform: linux/x86_64
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql_data:
